name: CodeHeroin
description: Javascript|Ruby|Vim
meta_description: "Kiran's Blog | He is a FullStack developer, works mainly on Javascript, Ruby | Linux | Vim | CLI"

markdown: kramdown
highlighter: pygments
logo: false
paginate: 15
permalink: :title.html
domain_name: 'https://codeheroin.com'
google_analytics: 'UA-97369059-1'
gems: 
  - jekyll-paginate
  - jekyll-sitemap

# Details for the RSS feed generator
url:            'https://codeheroin.com'
author:         'Kiran PS'
